name: Cronjob

on:
  schedule:
    - cron: "0 5 * * *"

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        name: Checkout repository

      - name: Run command
        run: echo "THIS IS TEST CRON JOB RUN"